name: CI

on:
  push:
    branches:
      - master

  pull_request:
  
  release:
    types: [published, created]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.11

    - name: Install dependencies
      run: |
        echo $CONDA/bin >> $GITHUB_PATH
        sudo apt update -y && sudo apt install -y libsndfile1
        conda env update --file environment.yml --name base

    - name: Run linter
      run: |
        pylint $GITHUB_WORKSPACE/kaldi_tflite

    - name: Run tests
      run: |
        PYTHONPATH=$GITHUB_WORKSPACE pytest -v
